# 4. Erinevuste, trendide ja seoste uurimine {.unnumbered}

::: {style="border: 2px dotted #555; padding: 10px; margin-bottom: 10px;"}
Käesolevas peatükis keskendume järgmistele küsimustele:

* Kuidas võrrelda erinevate gruppide tulemusi?
* Kuidas sõltub erinevuste uurimiseks kasutatav meetod tunnusetüübist?
* Milliseid graafilisi võimalusi on otstarbekas kasutada gruppidevaheliste erinevuste
uurimisel?
* Kuidas lahendada olukord, kui võrreldavate gruppide suurused ei ole võrdsed?
* Millisel juhul saab valimi keskmiste vahel olevat erinevust üldkogumile üldistada?
:::

## 4.1. Erinevuste uurimine kasutades keskväärtusi {.unnumbered .sub-title}

## 4.2. Erinevuste uurimine kasutades sagedusi ja protsente {.unnumbered .sub-title}

## 4.3. Erinevuste illustreerimine protsentuaalseid jaotusi võrdleva diagrammina {.unnumbered .sub-title}

## 4.4.\* Keskväärtuste vahelise erinevuse üldistamine: t-test {.unnumbered .sub-title}

## 4.5. Trendide e ajas toimuvate muutuste uurimine {.unnumbered .sub-title}

## 4.6. Seoste uurimine {.unnumbered .sub-title}

## 4.7. Kvalitatiivne sisuanalüüs {.unnumbered .sub-title}